language: go
sudo: false
go:
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/sys/unix

install:
  - go get github.com/lib/pq

script:
  - go build ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
